"""add kpi management tables

Revision ID: 1c7ed4748fc1
Revises: aaf73e35d6f8
Create Date: 2026-08-06 15:03:28.709438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '1c7ed4748fc1'
down_revision: Union[str, None] = 'aaf73e35d6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('parameters',
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('department_id', app.utils.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_parameters_department_id_departments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parameters')),
    sa.UniqueConstraint('department_id', 'name', name='uq_parameter_department_name')
    )
    op.create_index(op.f('ix_parameters_department_id'), 'parameters', ['department_id'], unique=False)
    op.create_table('kpi_indicators',
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('parameter_id', app.utils.types.GUID(), nullable=False),
    sa.Column('indicator_name', sa.String(length=255), nullable=False),
    sa.Column('annual_target', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('measurement_unit', sa.String(length=20), nullable=False),
    sa.Column('person_in_charge', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], name=op.f('fk_kpi_indicators_parameter_id_parameters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_indicators')),
    sa.UniqueConstraint('parameter_id', 'indicator_name', name='uq_indicator_parameter_name')
    )
    op.create_index(op.f('ix_kpi_indicators_parameter_id'), 'kpi_indicators', ['parameter_id'], unique=False)
    op.create_table('kpi_monthly_values',
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('indicator_id', app.utils.types.GUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['kpi_indicators.id'], name=op.f('fk_kpi_monthly_values_indicator_id_kpi_indicators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_monthly_values')),
    sa.UniqueConstraint('indicator_id', 'year', 'month', name='uq_monthly_value_indicator_year_month')
    )
    op.create_index(op.f('ix_kpi_monthly_values_indicator_id'), 'kpi_monthly_values', ['indicator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_monthly_values_indicator_id'), table_name='kpi_monthly_values')
    op.drop_table('kpi_monthly_values')
    op.drop_index(op.f('ix_kpi_indicators_parameter_id'), table_name='kpi_indicators')
    op.drop_table('kpi_indicators')
    op.drop_index(op.f('ix_parameters_department_id'), table_name='parameters')
    op.drop_table('parameters')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###