"""convert password reset to OTP code flow

Revision ID: 60d8bb4abf91
Revises: 9fe7abc9ef96
Create Date: 2026-08-02 19:44:28.446605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60d8bb4abf91'
down_revision: Union[str, None] = '9fe7abc9ef96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('code_hash', sa.String(length=255), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('password_reset_tokens', sa.Column('reset_token_hash', sa.String(length=255), nullable=True))
    op.add_column('password_reset_tokens', sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_password_reset_tokens_token_hash', table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_reset_token_hash'), 'password_reset_tokens', ['reset_token_hash'], unique=True)
    op.drop_column('password_reset_tokens', 'token_hash')
    op.drop_column('password_reset_tokens', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('password_reset_tokens', sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_password_reset_tokens_reset_token_hash'), table_name='password_reset_tokens')
    op.create_index('ix_password_reset_tokens_token_hash', 'password_reset_tokens', ['token_hash'], unique=True)
    op.drop_column('password_reset_tokens', 'reset_token_expires_at')
    op.drop_column('password_reset_tokens', 'reset_token_hash')
    op.drop_column('password_reset_tokens', 'verified_at')
    op.drop_column('password_reset_tokens', 'verified')
    op.drop_column('password_reset_tokens', 'attempts')
    op.drop_column('password_reset_tokens', 'code_expires_at')
    op.drop_column('password_reset_tokens', 'code_hash')
    # ### end Alembic commands ###