"""remove accepted_terms from users

Revision ID: 9fe7abc9ef96
Revises: b675226dc144
Create Date: 2026-07-31 17:37:01.982055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fe7abc9ef96'
down_revision: Union[str, None] = 'b675226dc144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_terms_at')
    op.drop_column('users', 'accepted_terms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_terms', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('accepted_terms_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###