"""add suspension and settings fields to users

Revision ID: aaf73e35d6f8
Revises: 60d8bb4abf91
Create Date: 2026-08-05 12:10:44.882932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = 'aaf73e35d6f8'
down_revision: Union[str, None] = '60d8bb4abf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('suspended_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('suspended_by_id', app.utils.types.GUID(), nullable=True))
    op.add_column('users', sa.Column('theme_preference', sa.String(length=20), nullable=False, server_default='system'))
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('users', 'theme_preference')
    op.drop_column('users', 'suspended_by_id')
    op.drop_column('users', 'suspended_reason')
    op.drop_column('users', 'suspended_at')
    op.drop_column('users', 'is_suspended')
    # ### end Alembic commands ###